# Generated by Django 3.2.9 on 2021-11-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('stats', '0001_initial'), ('stats', '0002_auto_20211111_1626'), ('stats', '0003_auto_20211111_1646'), ('stats', '0004_alter_record_temperature'), ('stats', '0005_auto_20211111_2343'), ('stats', '0006_auto_20211112_0018'), ('stats', '0007_alter_record_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('temperature', models.FloatField(null=True, verbose_name='Температура')),
                ('wind_direction', models.FloatField(null=True, verbose_name='Направление ветра в градусах')),
                ('wind_speed', models.IntegerField(verbose_name='Скорость ветра в м/с')),
                ('precipitation', models.FloatField(verbose_name='Атмосферные осадки в мм')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='Погода')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('city', 'date'), name='unique_city_date'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='city_record', to='stats.city', verbose_name='Город'),
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
